networks:
  anvil-net:
    driver: bridge

volumes:
  anvil:

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.5.1
    restart: unless-stopped
    entrypoint: ["/work/scripts/anvil-entrypoint.sh"]
    env_file:
      - .env
    environment:
      # where snapshot lives on host
      STATE_PATH: "/config/anvil-state.json"
    volumes:
      - ./config:/config
      - ./scripts:/work/scripts:ro
    ports:
      - "${L1_RPC_PORT}:${L1_RPC_PORT}"
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:${L1_RPC_PORT}"]
      interval: 2s
      timeout: 3s
      retries: 10
