services:
  # op-geth-init:
  #   image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101602.3
  #   entrypoint: ["/bin/sh", "-c"]
  #   command:
  #     - |
  #       if [ -f /data/geth/chaindata/CURRENT ] || [ -d /data/geth/chaindata ]; then
  #         echo "op-geth already initialized, skipping genesis init"
  #       else
  #         echo "Initializing op-geth with genesis..."
  #         geth init --datadir=/data /config/genesis.json
  #       fi
  #   volumes:
  #     - op-geth-data:/data
  #     - ./genesis.json:/config/42069-genesis.json:ro

  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.5.1
    restart: unless-stopped
    entrypoint: ["/work/scripts/anvil-entrypoint.sh"]
    env_file:
      - .env
    environment:
      # where snapshot lives on host
      STATE_PATH: "/config/anvil-state.json"
    volumes:
      - ./config:/config
      - ./scripts:/work/scripts:ro
    ports:
      - "${L1_RPC_PORT}:${L1_RPC_PORT}"
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:${L1_RPC_PORT}"]
      interval: 2s
      timeout: 3s
      retries: 10

  op-deployer-init:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-deployer:v0.5.2
    depends_on:
      anvil:
        condition: service_healthy
    volumes:
      - ./config:/config
      - ./scripts:/work/scripts:ro
    env_file:
      - .env
    environment:
      L1_RPC_URL: "http://anvil:${L1_RPC_PORT}"
      WORKDIR: "/config"
    command: ["/work/scripts/init-op-contracts-on-l1.sh"]
