#!/bin/sh
set -eu

# -----------------------------------------------------------------------------
# One-time init script intended to run INSIDE:
#   us-docker.pkg.dev/oplabs-tools-artifacts/images/op-deployer:v0.5.2
#
# Requirements in image: op-deployer, sed/awk/grep/coreutils (present)
# No jq/python/curl/openssl assumed.
#
# Artifacts written to WORKDIR (default: /config), which should be a host bind mount.
# -----------------------------------------------------------------------------

WORKDIR="${WORKDIR:-/config}"

log()  { printf '%s\n' "$*"; }
die()  { log "[ERROR] $*"; exit 1; }
step() { log ""; log "==> $*"; }

command -v op-deployer >/dev/null 2>&1 || die "op-deployer not found in image"

# One-time guard
mkdir -p "$WORKDIR"

if [ -s "${WORKDIR}/state.json" ] || [ -s "${WORKDIR}/intent.toml" ] || \
   [ -s "${WORKDIR}/${L2_CHAIN_ID}-genesis.json" ] || [ -s "${WORKDIR}/${L2_CHAIN_ID}-rollup.json" ]; then
  log "[SKIP] Artifacts already exist in ${WORKDIR}. (Delete ./config/* to regenerate.)"
  exit 0
fi

step "Writing jwt.txt from JWT_SECRET env var"
# Write exactly what you provide; ensure newline at end
printf '%s\n' "$JWT_SECRET" > "${WORKDIR}/jwt.txt"

step "Running op-deployer init"
op-deployer init \
  --l1-chain-id "${L1_CHAIN_ID}" \
  --l2-chain-ids "${L2_CHAIN_ID}" \
  --workdir "${WORKDIR}" \
  --intent-type "custom"

[ -f "${WORKDIR}/intent.toml" ] || die "intent.toml not generated by op-deployer init"

step "Backing up generated intent.toml"
cp "${WORKDIR}/intent.toml" "${WORKDIR}/intent.toml.initial"

# Convert L2 chain ID to 32-byte padded hex (0x + 64 hex chars)
L2_CHAIN_ID_HEX="$(printf "0x%064x" "${L2_CHAIN_ID}")"
log "[INFO] L2 Chain ID: ${L2_CHAIN_ID} -> ${L2_CHAIN_ID_HEX}"

step "Writing customized intent.toml"
cat > "${WORKDIR}/intent.toml" <<EOF
# Generated by op_deployer_init.sh
configType = "custom"
l1ChainID = ${L1_CHAIN_ID}
fundDevAccounts = true

# Contract artifact locators
l1ContractsLocator = "embedded"
l2ContractsLocator = "embedded"

[superchainRoles]
  SuperchainProxyAdminOwner = "${ADMIN_ADDRESS}"
  SuperchainGuardian = "${ADMIN_ADDRESS}"
  ProtocolVersionsOwner = "${ADMIN_ADDRESS}"
  Challenger = "${CHALLENGER_ADDRESS}"

[[chains]]
  id = "${L2_CHAIN_ID_HEX}"
  baseFeeVaultRecipient = "${FEE_RECIPIENT_ADDRESS}"
  l1FeeVaultRecipient = "${FEE_RECIPIENT_ADDRESS}"
  sequencerFeeVaultRecipient = "${FEE_RECIPIENT_ADDRESS}"
  operatorFeeVaultRecipient = "${FEE_RECIPIENT_ADDRESS}"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  gasLimit = 60000000

  [chains.roles]
    l1ProxyAdminOwner = "${ADMIN_ADDRESS}"
    l2ProxyAdminOwner = "${ADMIN_ADDRESS}"
    systemConfigOwner = "${ADMIN_ADDRESS}"
    unsafeBlockSigner = "${SEQUENCER_ADDRESS}"
    batcher = "${BATCHER_ADDRESS}"
    proposer = "${PROPOSER_ADDRESS}"
    challenger = "${CHALLENGER_ADDRESS}"

  [chains.dangerousAltDAConfig]
    useAltDA = true
    daCommitmentType = "${ALTDA_COMMITMENT_TYPE}"
    daChallengeWindow = ${ALTDA_CHALLENGE_WINDOW}
    daResolveWindow = ${ALTDA_RESOLVE_WINDOW}
    daBondSize = 0
    daResolverRefundPercentage = 0
EOF

step "Running op-deployer apply"
op-deployer apply \
  --workdir "${WORKDIR}" \
  --l1-rpc-url "${L1_RPC_URL}" \
  --private-key "${DEPLOYER_PRIVATE_KEY}"

[ -f "${WORKDIR}/state.json" ] || die "state.json not found after apply"

# -----------------------------------------------------------------------------
# Inspect genesis + rollup
# If inspect fails, we keep the error output in the target file for debugging.
# -----------------------------------------------------------------------------
GENESIS_FILE="${WORKDIR}/${L2_CHAIN_ID}-genesis.json"
ROLLUP_FILE="${WORKDIR}/${L2_CHAIN_ID}-rollup.json"

step "Generating L2 genesis (inspect genesis)"
if op-deployer inspect genesis --workdir "${WORKDIR}" "${L2_CHAIN_ID}" > "${GENESIS_FILE}" 2>&1; then
  log "[OK] Wrote ${GENESIS_FILE}"
else
  log "[ERROR] Failed to generate genesis; error output saved in ${GENESIS_FILE}"
  # Show tail for quick signal
  tail -n 80 "${GENESIS_FILE}" 2>/dev/null || true
  die "inspect genesis failed (likely requires state.json patching)"
fi

step "Generating rollup config (inspect rollup)"
if op-deployer inspect rollup --workdir "${WORKDIR}" "${L2_CHAIN_ID}" > "${ROLLUP_FILE}" 2>&1; then
  log "[OK] Wrote ${ROLLUP_FILE}"
else
  log "[ERROR] Failed to generate rollup config; error output saved in ${ROLLUP_FILE}"
  tail -n 80 "${ROLLUP_FILE}" 2>/dev/null || true
  die "inspect rollup failed"
fi

# Verify alt_da present (best effort)
if grep -q "alt_da" "${ROLLUP_FILE}" 2>/dev/null; then
  log "[OK] Alt-DA configuration present in rollup config"
  grep -n "alt_da" -A5 "${ROLLUP_FILE}" | head -n 25 || true
fi

step "Fixing ownership/permissions on /config for host git usage"

# If these are provided (recommended), use them:
HOST_UID="${HOST_UID:-1000}"
HOST_GID="${HOST_GID:-1000}"

# Make files readable and dirs traversable; jwt.txt should be world-readable per your request
chown -R "${HOST_UID}:${HOST_GID}" /config 2>/dev/null || true
chmod -R u+rwX,go+rX /config 2>/dev/null || true
chmod 644 /config/jwt.txt 2>/dev/null || true

step "Done. Files in ${WORKDIR}:"
ls -la "${WORKDIR}"
