#!/bin/bash
# TODO: see https://github.com/nuke-web3/op-celestia-devnet/ for scripts!
# GOALS:
# - startup anvil via compose (it should check for artifacts from running this init and WARN and exit script early if so)
# - run op-deployer init & intent stuff
# - deploy on anvil
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
load_env

# TODO: starup anvil via docker compose
 
# Check Anvil is running
if ! curl -s -o /dev/null "${L1_RPC_URL}"; then
    log_error "L1 RPC not accessible at ${L1_RPC_URL}"
    exit 1
fi
log_success "L1 RPC is accessible"

# Create deployment directory
mkdir -p "${DEPLOYMENTS_DIR}"

log_step "Generating JWT secret..."
generate_jwt_secret # TODO: maybe just hardcoded? Valid example: (0501582be00a740fb7b78914c9a497e820394034a33bd3f00c5ddef4173e8964
)
log_step "Initializing deployment with op-deployer init..."

# op-deployer init generates intent.toml and state.json in workdir
# We use --intent-type custom so we can modify it afterwards
${OP_DEPLOYER} init \
    --l1-chain-id "${L1_CHAIN_ID}" \
    --l2-chain-ids "${L2_CHAIN_ID}" \
    --workdir "${DEPLOYMENTS_DIR}" \
    --intent-type "custom"

log_success "Deployment initialized"

log_step "Customizing intent.toml..."

INTENT_FILE="${DEPLOYMENTS_DIR}/intent.toml"

if [[ ! -f "${INTENT_FILE}" ]]; then
    log_error "intent.toml not generated by op-deployer init"
    exit 1
fi

# Back up the generated intent
cp "${INTENT_FILE}" "${INTENT_FILE}.initial"

# Convert L2 chain ID to padded hex (32 bytes = 64 hex chars with 0x prefix)
# Example: 42069 -> 0x000000000000000000000000000000000000000000000000000000000000a455
L2_CHAIN_ID_HEX=$(printf "0x%064x" "${L2_CHAIN_ID}")
log_info "L2 Chain ID: ${L2_CHAIN_ID} -> ${L2_CHAIN_ID_HEX}"

# Create our customized intent.toml
# Field names must match op-deployer's expected schema (see generated template)
cat > "${INTENT_FILE}" << EOF
# Generated by init-op-contracts-on-l1.sh
configType = "custom"
l1ChainID = ${L1_CHAIN_ID}
fundDevAccounts = true

# Contract artifact locators
# https://docs.optimism.io/chain-operators/tools/op-deployer/reference/artifacts-locators
l1ContractsLocator = "embedded"
l2ContractsLocator = "embedded"

[superchainRoles]
  SuperchainProxyAdminOwner = "${ADMIN_ADDRESS}"
  SuperchainGuardian = "${ADMIN_ADDRESS}"
  ProtocolVersionsOwner = "${ADMIN_ADDRESS}"
  Challenger = "${CHALLENGER_ADDRESS}"

# Chain configuration
[[chains]]
  # Chain ID must be 32-byte padded hex string with 0x prefix
  id = "${L2_CHAIN_ID_HEX}"
  baseFeeVaultRecipient = "${FEE_RECIPIENT_ADDRESS}"
  l1FeeVaultRecipient = "${FEE_RECIPIENT_ADDRESS}"
  sequencerFeeVaultRecipient = "${FEE_RECIPIENT_ADDRESS}"
  operatorFeeVaultRecipient = "${FEE_RECIPIENT_ADDRESS}"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  gasLimit = 60000000

  [chains.roles]
    l1ProxyAdminOwner = "${ADMIN_ADDRESS}"
    l2ProxyAdminOwner = "${ADMIN_ADDRESS}"
    systemConfigOwner = "${ADMIN_ADDRESS}"
    unsafeBlockSigner = "${SEQUENCER_ADDRESS}"
    batcher = "${BATCHER_ADDRESS}"
    proposer = "${PROPOSER_ADDRESS}"
    challenger = "${CHALLENGER_ADDRESS}"

  [chains.deployOverrides]
    l2BlockTime = ${L2_BLOCK_TIME}
    l2GenesisBlockGasLimit = 60000000
    systemConfigStartBlock = 0
    finalizationPeriodSeconds = 12
    # l2GenesisBlockBaseFeePerGas must be a hex string
    l2GenesisBlockBaseFeePerGas = "0x3B9ACA00"

  # Alt-DA Configuration for Celestia
  # This enables the DataAvailabilityChallenge contract and Alt-DA mode
  [chains.dangerousAltDAConfig]
    useAltDA = true
    daCommitmentType = "${ALTDA_COMMITMENT_TYPE}"
    daChallengeWindow = ${ALTDA_CHALLENGE_WINDOW}
    daResolveWindow = ${ALTDA_RESOLVE_WINDOW}
    daBondSize = 0
    daResolverRefundPercentage = 0
EOF

log_success "Customized intent.toml"
log_info "Intent file: ${INTENT_FILE}"

# TODO: would be nice to check if the original intent we backed up had missing or changed fields here.

# -----------------------------------------------------------------------------
# Apply deployment (deploy contracts)
# -----------------------------------------------------------------------------

log_step "Deploying contracts (this may take a few minutes)..."
log_info "Running: op-deployer apply"

${OP_DEPLOYER} apply \
    --workdir "${DEPLOYMENTS_DIR}" \
    --l1-rpc-url "${L1_RPC_URL}" \
    --private-key "${DEPLOYER_PRIVATE_KEY}"

log_success "Contracts deployed!"

log_step "Extracting deployment artifacts..."

STATE_FILE="${DEPLOYMENTS_DIR}/state.json"

# Check for state.json
if [[ ! -f "${STATE_FILE}" ]]; then
    log_error "state.json not found after deployment"
    exit 1
fi

log_step "Generating L2 genesis and rollup config..."

GENESIS_FILE="${DEPLOYMENTS_DIR}/${L2_CHAIN_ID}-genesis.json"
ROLLUP_FILE="${DEPLOYMENTS_DIR}/${L2_CHAIN_ID}-rollup.json"

# TODO: is this fix really needed? new op-deployer released to test, once past rc
# https://github.com/ethereum-optimism/optimism/releases/tag/op-deployer%2Fv0.6.0-rc.3
# 
# Fix for op-deployer bug: deployOverrides with numeric values cause genesis generation to fail
# We need to remove them from appliedIntent before generating genesis
log_info "Preparing state for genesis generation..."
cp "${STATE_FILE}" "${STATE_FILE}.bak"
jq 'del(.appliedIntent.chains[0].deployOverrides)' "${STATE_FILE}" > "${STATE_FILE}.tmp" && \
    mv "${STATE_FILE}.tmp" "${STATE_FILE}"

# Generate genesis
log_info "Running: op-deployer inspect genesis"
if ${OP_DEPLOYER} inspect genesis --workdir "${DEPLOYMENTS_DIR}" "${L2_CHAIN_ID}" > "${GENESIS_FILE}" 2>&1; then
    log_success "L2 genesis: ${GENESIS_FILE}"
else
    log_error "Failed to generate genesis"
    cat "${GENESIS_FILE}"
fi

# Generate rollup config
log_info "Running: op-deployer inspect rollup"
if ${OP_DEPLOYER} inspect rollup --workdir "${DEPLOYMENTS_DIR}" "${L2_CHAIN_ID}" > "${ROLLUP_FILE}" 2>&1; then
    log_success "Rollup config: ${ROLLUP_FILE}"
else
    log_error "Failed to generate rollup config"
    cat "${ROLLUP_FILE}"
fi

# Restore original state.json
mv "${STATE_FILE}.bak" "${STATE_FILE}"

# Verify genesis has alt_da config
if grep -q "alt_da" "${ROLLUP_FILE}" 2>/dev/null; then
    log_success "Alt-DA configuration present in rollup config"
    grep -A5 "alt_da" "${ROLLUP_FILE}" | head -6
fi

# List what was generated
echo ""
log_info "Files in deployment directory:"
ls -la "${DEPLOYMENTS_DIR}/"

log_success "L1 contracts deployed successfully!"

# TODO: use anvil to dump state
